apiVersion: v1
data:
  postgresql-password: MDJyc2RPcUlOMw==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-12-23T17:34:23Z"
  labels:
    app: postgresql
    app.kubernetes.io/managed-by: Helm
    chart: postgresql-6.5.0
    heritage: Helm
    release: my-release
  name: my-release-postgresql
  namespace: default
  resourceVersion: "866263"
  uid: 4ab45ce1-af4f-4ef8-8f47-9c8d014ca96c
type: Opaque
