apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-postgres-pv
  labels:
    type: local
    app: postgresql
    release: my-release
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
